name: EasyKits
version: 2.3.1
main: org.trentech.easykits.Main
api-version: 1.13
authors: [TrenTech]
description: Kits for all!
website: trentech.org
softdepend: [Vault]
commands:
  kit:
    description: Kits command
    usage: </command>
    aliases: [easykits,k]